#!/usr/bin/env bash
# Mechanical contract for cto-orchestration's agentctl lanes and goal paths.
set -u
cd "$(dirname "$0")"
. ./lib-testkit.sh

SKILL="../skills/cto-orchestration/SKILL.md"
GOAL="../skills/cto-orchestration/references/goal-template.md"
REVIEW="../skills/cto-orchestration/references/review-dispatch.md"
DEXEC="../skills/cto-orchestration/references/agent-watch/dispatch-exec"
AGENTCTL_SRC="../skills/cto-orchestration/references/agent-watch/agentctl"
DUPLEXCTL="../skills/cto-orchestration/references/agent-watch/duplexctl.py"
PREFLIGHT="../skills/cto-orchestration/references/goal-preflight.py"
QUEUE="../skills/cto-orchestration/references/decision-queue.md"
RETRO="../skills/cto-orchestration/references/retrospective.md"
skill_body="$(cat "$SKILL")"
goal_body="$(cat "$GOAL")"
review_body="$(cat "$REVIEW")"
dexec_body="$(cat "$DEXEC")"
agentctl_body="$(cat "$AGENTCTL_SRC")"
duplexctl_body="$(cat "$DUPLEXCTL")"
preflight_body="$(cat "$PREFLIGHT")"
queue_body="$(cat "$QUEUE")"
retro_body="$(cat "$RETRO")"
readme_body="$(cat ../skills/cto-orchestration/references/agent-watch/README.md)"

echo "== cto docs contract =="
chk_contains "unified surface is agentctl" "agentctl start|steer|status|watch|stop" "$skill_body"
chk_contains "duplex is the omp/claude default" "duplex（默认：omp / claude）" "$skill_body"
chk_contains "round is the codex default and recovery leg" "round（默认：codex；亦是全引擎崩溃恢复腿）" "$skill_body"
chk_contains "duplex steer reachable mid-turn" "轮内随时可达" "$skill_body"
chk_contains "round is self-contained per round" "单轮不交互" "$skill_body"
chk_contains "TUI lane is retired" "TUI 车道已于本大版本裁撤" "$skill_body"
chk_contains "file deliverables require the gate" '文件任务必须声明 `--deliverable <glob>`' "$skill_body"
chk_contains "deliverable glob is session-cwd relative" "相对 glob 按会话 cwd 解析" "$skill_body"
chk_contains "non-file results omit the gate" "非文件结果不带" "$skill_body"
chk_contains "subagent owns browser MCP isolated reads" "浏览器 / MCP / 隔离主上下文的读密集工作" "$skill_body"
chk_contains "start does not auto-watch" "不会自动 watch" "$skill_body"
chk_contains "round RUNNING steer is rejected" "RUNNING 轮不读 stdin" "$skill_body"
chk_contains "delivery is not obedience" "投递成功 ≠ 模型照做" "$skill_body"
chk_contains "runtime rejects RUNNING send" "previous round of" "$dexec_body"
chk_contains "implementation detail is progressively loaded" "references/implementation-discipline.md" "$skill_body"
chk_contains "high-uncertainty work selects preflight gate" '`--require-preflight`' "$skill_body"
chk_contains "round lane consumes preflight flag" '--require-preflight) REQUIRE_PREFLIGHT=1' "$dexec_body"
chk_contains "duplex lane consumes preflight flag" '--require-preflight) PREFLIGHT=1' "$agentctl_body"
chk_contains "both lanes call canonical preflight validator" '../goal-preflight.py' "$dexec_body$agentctl_body"
chk_contains "validator rejects unresolved evidence" "unresolved/N/A is not evidence" "$preflight_body"
chk_contains "duplex single fifo writer is flock-serialized" "flock" "$duplexctl_body"
chk_contains "duplex output is bounded by design" "SUMMARY_CHARS" "$duplexctl_body"

chk_contains "goal read and deliverable paths are absolute" "所有“先读路径”和“交付物路径”必须写绝对路径" "$goal_body"
chk_contains "goal exempts command arguments" "不要求证明命令内部每个参数都绝对化" "$goal_body"
chk_contains "findings uses absolute placeholder" "/absolute/path/to/worktree/docs/orchestration/" "$goal_body"
chk_contains "goal delegates understanding gate to runtime" "复述 / 立即开工 / BLOCKED 协议由 runtime" "$goal_body"
chk_contains "runtime headless understanding gate starts" "Do not wait for approval or interaction" "$dexec_body"
chk_contains "runtime blocker path uses canonical cwd" '$cwd/BLOCKED.md' "$dexec_body"
chk_contains "goal has conditional premises section" "Premises this goal rests on (VERIFY — do not trust)" "$goal_body"
chk_contains "premise evidence is candidate not verdict" "candidate evidence" "$goal_body"
chk_contains "false premise stops implementation" "任何 premise 为假 → **STOP AND REPORT**" "$goal_body"
chk_contains "premises carry claim and verify checkbox" '- [ ] **Claim**:' "$goal_body"
chk_contains "refuted audit claims return to source doc" 'REFUTED CLAIMS' "$skill_body"
chk_contains "refuted table has required columns" "claim / evidence / pointer" "$skill_body"
chk_contains "SKILL runtime gate wording" "runtime footer 要求简短复述后立即开工" "$skill_body"
chk_not_contains "README has no blanket wait gate" "核对无误再放行" "$readme_body"
chk_contains "README duplex protocol footer" "HEADLESS 协议 footer" "$readme_body"
chk_contains "README keeps ENGINE-SILENT honesty" "ENGINE-SILENT" "$readme_body"
chk_contains "README keeps notification black-hole evidence" "完成通知黑洞" "$readme_body"
chk_contains "README keeps send-keys pitfall census for guard pointer" "裸 send-keys 坑枚举" "$readme_body"
chk_not_contains "relative-path contract removed" "Paths relative to" "$goal_body"

chk_contains "queue admits no generic T1 ledger hook" "尚无通用 T1 自动记账 / T2 deny" "$queue_body"
chk_contains "queue freshness is reminder only" "提醒，不冒充权限门" "$queue_body"
chk_contains "queue is active-only" "只存活跃项" "$queue_body"
chk_contains "queue hook covers new context" "SessionStart + UserPromptSubmit" "$queue_body"
chk_contains "retro cleared history is blocking" "已清区仍有正文”返回 blocking FAIL" "$queue_body"
chk_contains "retro queue freshness remains warning" "队列仅不新鲜仍只告警、exit 0" "$queue_body"
chk_contains "retro hard failures are scoped" "是 blocking FAIL" "$retro_body"
chk_contains "retro soft checks admit exit zero" "只给 warning，exit 仍可为 0" "$retro_body"
chk_not_contains "retro does not call every check a hard gate" "未全过不算复盘完成" "$retro_body"

value_gate='Value gate: <existing gap → incremental value>; Preflight: <cheapest read-only falsifier actually run> => <observed result>'
chk_eq "goal has exactly one conditional value-gate line" 1 "$(grep -cF "$value_gate" "$GOAL")"
chk_contains "value gate targets uncertain expensive direction" "高不确定方向准备进入昂贵设计/实现" "$goal_body"
chk_contains "value gate requires probe before dispatch" "先跑最便宜证伪" "$goal_body"
chk_contains "ordinary work deletes value gate" "普通 bugfix、机械改动和纯研究删除它" "$goal_body"
chk_not_contains "goal has no fixed Existing coverage field" "Existing coverage:" "$goal_body"
chk_not_contains "goal has no fixed Incremental value field" "Incremental value:" "$goal_body"
chk_not_contains "goal has no fixed Cheapest falsification field" "Cheapest falsification" "$goal_body"
chk_not_contains "goal has no fixed Stop-loss field" "Stop-loss:" "$goal_body"
chk_contains "review loop launch is explicit" "--workflow review-loop" "$review_body"
chk_contains "review loop launch requires max rounds" "--max-rounds <N>" "$review_body"
chk_contains "review loop runtime meta is sole source" "stop-loss 只认 runtime exec.meta" "$review_body"
chk_contains "review round 3 requires continuation lease" '第 3 轮起每轮续派须在 brief 写 `SHIP-BLOCKING: <依据>`' "$skill_body"
chk_contains "self-growing review fixes stop after two rounds" '连续 2 轮只新增 finding，则止损并转人工裁决或 accept-documented' "$skill_body"
chk_contains "goal does not duplicate review rounds" "本 GOAL 不复制轮数" "$goal_body"
chk_contains "runtime persists workflow" "workflow=%s" "$dexec_body"
chk_contains "runtime persists max rounds" "max_rounds=%s" "$dexec_body"
chk_contains "runtime owns budget exhausted" "BUDGET-EXHAUSTED" "$dexec_body"

summary
